INSERT INTO ProductSchema.Categories (CategoryName) VALUES 
('Electronics'), 
('Furniture'), 
('Clothing'), 
('Toys'), 
('Books'), 
('Appliances'), 
('Tools'), 
('Groceries'), 
('Beauty'), 
('Health'), 
('Jewelry'), 
('Sports'), 
('Automotive'), 
('Office Supplies'), 
('Garden'), 
('Pet Supplies'), 
('Baby Products'), 
('Music'), 
('Movies'), 
('Games');