OPEN MASTER KEY DECRYPTION BY PASSWORD = 'Password!123';
OPEN SYMMETRIC KEY PhoneKey
DECRYPTION BY CERTIFICATE PhoneCertificate;

UPDATE UserSchema.Users
SET PhoneEncrypted = ENCRYPTBYKEY(Key_GUID('PhoneKey'), Phone);

CLOSE SYMMETRIC KEY PhoneKey;